{% set name = "mpl-scatter-density" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl-scatter-density-{{ version }}.tar.gz
  sha256: cace750887916d3881b3a42ab5805769cc8d7eb70ef610938cbb57c967277620

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base >=3.0
    - fast-histogram >=0.3

test:
  imports:
    - mpl_scatter_density
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astrofrog/mpl-scatter-density
  summary: Matplotlib helpers to make density scatter plots
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
